/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.toko_tubes;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;


/**
 *
 * @author DEWATA
 */
public class Dashboard extends javax.swing.JFrame {

    private final Pembelian beli;
    private final Penjualan jual;
    private final StokBarang sb = new StokBarang();
    private final Transaksi T = new Transaksi();
    private final detail dt = new detail();
    private int IDPetugas;
    
    public Dashboard(int IDPetugas) {
        initComponents();
        this.beli = new Pembelian(IDPetugas);
        this.jual = new  Penjualan(IDPetugas);
        this.IDPetugas = IDPetugas;

    }
 private void display(JPanel panel){
    jPanel3.removeAll();
    jPanel3.setLayout(new BorderLayout());
    jPanel3.add(panel, BorderLayout.CENTER);
    jPanel3.revalidate();
    jPanel3.repaint();
    this.pack();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PenButton = new javax.swing.JButton();
        PemButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        SBbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TransaksiButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOKO KELONTONG PAK DHE");
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText(" Dashboard");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEWATA\\Documents\\NetBeansProjects\\TOKO_TUBES\\src\\vecteezy_coffee-shop-logo_23617247 (1).png")); // NOI18N

        PenButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PenButton.setText("PENJUALAN");
        PenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PenButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PenButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PenButtonMouseExited(evt);
            }
        });
        PenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenButtonActionPerformed(evt);
            }
        });

        PemButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PemButton.setText("PEMBELIAN");
        PemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PemButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PemButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PemButtonMouseExited(evt);
            }
        });
        PemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("(Manajer)");

        SBbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SBbutton.setText("Stok Barang");
        SBbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SBbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SBbuttonMouseExited(evt);
            }
        });
        SBbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBbuttonActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TransaksiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TransaksiButton.setText("TRANSAKSI");
        TransaksiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransaksiButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransaksiButtonMouseExited(evt);
            }
        });
        TransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Detail Transaksi");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PenButton)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel9)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TransaksiButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SBbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(PenButton)
                .addGap(18, 18, 18)
                .addComponent(PemButton)
                .addGap(18, 18, 18)
                .addComponent(SBbutton)
                .addGap(18, 18, 18)
                .addComponent(TransaksiButton)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(980, 700));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenButtonActionPerformed

    private void PemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemButtonActionPerformed

    }//GEN-LAST:event_PemButtonActionPerformed

    private void PemButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemButtonMouseEntered
        PemButton.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_PemButtonMouseEntered

    private void PemButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemButtonMouseExited
        PemButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PemButtonMouseExited

    private void PenButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenButtonMouseEntered
        PenButton.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_PenButtonMouseEntered

    private void PenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenButtonMouseExited
        PenButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PenButtonMouseExited

    private void PemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemButtonMouseClicked
        PemButton.setBackground(new Color(0, 255, 255));

        display(beli);
    }//GEN-LAST:event_PemButtonMouseClicked

    private void PenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenButtonMouseClicked
        PenButton.setBackground(new Color(0, 255, 255));

        display(jual);
    }//GEN-LAST:event_PenButtonMouseClicked

    private void SBbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBbuttonMouseEntered
        SBbutton.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_SBbuttonMouseEntered

    private void SBbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBbuttonMouseExited
        SBbutton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_SBbuttonMouseExited

    private void SBbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBbuttonActionPerformed

        display(sb);
    }//GEN-LAST:event_SBbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         this.dispose();
        LoginFrame LoginPage = new LoginFrame();
        LoginPage.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void TransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiButtonActionPerformed
        display(T);
    }//GEN-LAST:event_TransaksiButtonActionPerformed

    private void TransaksiButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiButtonMouseEntered
        TransaksiButton.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_TransaksiButtonMouseEntered

    private void TransaksiButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiButtonMouseExited
        TransaksiButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_TransaksiButtonMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        display(dt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton3MouseExited

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int IDPetugas=123;
                new Dashboard(IDPetugas).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PemButton;
    private javax.swing.JButton PenButton;
    private javax.swing.JButton SBbutton;
    private javax.swing.JButton TransaksiButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
