/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.toko_tubes;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEWATA
 */
public class detail extends javax.swing.JPanel {

    private Connection connection;
    private PreparedStatement preparedStatement;
    private ResultSet resultSet;
    public detail() {
        initComponents();
        try { 
          connection = DBStock.BukaKoneksi();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetailPembelianTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        DetailPenjualanTable = new javax.swing.JTable();
        ButtonPembeliandt = new javax.swing.JButton();
        ButtonPenjualandt = new javax.swing.JButton();

        detailPanel.setBackground(new java.awt.Color(0, 51, 153));
        detailPanel.setPreferredSize(new java.awt.Dimension(980, 700));
        detailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Detail Transaksi Penjualan");
        detailPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Detail Transaksi Pembelian");
        detailPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        DetailPembelianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Detail Transaksi", "ID Transaksi Pembelian", "ID Barang", "Jumlah Barang", "Total"
            }
        ));
        jScrollPane1.setViewportView(DetailPembelianTable);

        detailPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 970, 280));

        DetailPenjualanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Detail Transaksi", "ID Transaksi Penjualan", "ID Barang", "Jumlah Barang", "Total"
            }
        ));
        jScrollPane3.setViewportView(DetailPenjualanTable);

        detailPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 970, 280));

        ButtonPembeliandt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonPembeliandt.setText("TAMPILKAN");
        ButtonPembeliandt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPembeliandtActionPerformed(evt);
            }
        });
        detailPanel.add(ButtonPembeliandt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));

        ButtonPenjualandt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonPenjualandt.setText("TAMPILKAN");
        ButtonPenjualandt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPenjualandtActionPerformed(evt);
            }
        });
        detailPanel.add(ButtonPenjualandt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPembeliandtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPembeliandtActionPerformed
        try {
            String query = "SELECT id_detail_transaksi, id_transaksi_pembelian, id_barang, jumlah_barang, subtotal FROM detail_transaksi_pembelian";
            preparedStatement = connection.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DefaultTableModel model = (DefaultTableModel) DetailPembelianTable.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                int iddtTransaksi = resultSet.getInt("id_detail_transaksi");
                int idTransaksi = resultSet.getInt("id_transaksi_pembelian");
                int id_barang = resultSet.getInt("id_barang");
                int jumlah = resultSet.getInt("jumlah_barang");
                int total = resultSet.getInt("subtotal");

                model.addRow(new Object[]{iddtTransaksi, idTransaksi, id_barang, jumlah, total});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ButtonPembeliandtActionPerformed

    private void ButtonPenjualandtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPenjualandtActionPerformed
        try {
            String query = "SELECT id_detail_transaksi, id_transaksi_penjualan, id_barang, jumlah_barang, subtotal FROM detail_transaksi_penjualan";
            preparedStatement = connection.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DefaultTableModel model = (DefaultTableModel) DetailPenjualanTable.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                int iddtTransaksi = resultSet.getInt("id_detail_transaksi");
                int idTransaksi = resultSet.getInt("id_transaksi_penjualan");
                int id_barang = resultSet.getInt("id_barang");
                int jumlah = resultSet.getInt("jumlah_barang");
                int total = resultSet.getInt("subtotal");

                model.addRow(new Object[]{iddtTransaksi, idTransaksi, id_barang, jumlah, total});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ButtonPenjualandtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPembeliandt;
    private javax.swing.JButton ButtonPenjualandt;
    private javax.swing.JTable DetailPembelianTable;
    private javax.swing.JTable DetailPenjualanTable;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
