/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.toko_tubes;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DEWATA
 */
public class LoginFrame extends javax.swing.JFrame {

    private Connection connection;
    public LoginFrame() {
        initComponents();
        panelLogin.setBackground(new Color(0,0,0,50));
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        gradientLogin1 = new com.mycompany.toko_tubes.GradientLogin();
        panelLogin = new com.mycompany.toko_tubes.PanelLoginCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ausername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginClick = new javax.swing.JButton();
        Apassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOKO KELONTONG PAK DHE");
        setBackground(new java.awt.Color(102, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBackground.setBackground(new java.awt.Color(255, 102, 102));

        gradientLogin1.setColorEnd(new java.awt.Color(102, 102, 255));
        gradientLogin1.setColorStart(new java.awt.Color(0, 204, 255));

        panelLogin.setBackground(new java.awt.Color(102, 102, 255));
        panelLogin.setRoundBottomLeft(50);
        panelLogin.setRoundBottomRight(50);
        panelLogin.setRoundTopLeft(50);
        panelLogin.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        Ausername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AusernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        LoginClick.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LoginClick.setText("LOGIN");
        LoginClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginClickMouseClicked(evt);
            }
        });
        LoginClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginClickActionPerformed(evt);
            }
        });

        Apassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApasswordActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEWATA\\Documents\\NetBeansProjects\\TOKO_TUBES\\src\\png-transparent-computer-icons-security-privacy-key-icon-text-vector-icons-property-removebg-preview (1).png")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(17, 17));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEWATA\\Documents\\NetBeansProjects\\TOKO_TUBES\\src\\Avatar__myself__people__profile__username_icon_-_Download_on_Iconfinder-removebg-preview (1).png")); // NOI18N
        jLabel5.setText("jLabel4");
        jLabel5.setPreferredSize(new java.awt.Dimension(17, 17));

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel1))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(LoginClick, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Ausername)
                                .addComponent(Apassword, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ausername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Apassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(LoginClick, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gradientLogin1Layout = new javax.swing.GroupLayout(gradientLogin1);
        gradientLogin1.setLayout(gradientLogin1Layout);
        gradientLogin1Layout.setHorizontalGroup(
            gradientLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientLogin1Layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        gradientLogin1Layout.setVerticalGroup(
            gradientLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientLogin1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout PanelBackgroundLayout = new javax.swing.GroupLayout(PanelBackground);
        PanelBackground.setLayout(PanelBackgroundLayout);
        PanelBackgroundLayout.setHorizontalGroup(
            PanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBackgroundLayout.setVerticalGroup(
            PanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientLogin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginClickActionPerformed
        // TODO add your handling code here:
        String username = Ausername.getText();
        String password = Apassword.getText(); // Retrieve password correctly
        String userRole = getUserRole(username, password);
        
        int IDPetugas = getIDPetugasDatabase(username, password);
        if (userRole != null) {
            this.dispose(); // Close the login frame
            if (userRole.equals("Manajer")) {
                Dashboard adminDashboardFrame = new Dashboard(IDPetugas);
                adminDashboardFrame.setVisible(true);
            } else if (userRole.equals("Kasir")) {
                
                DashboardPetugas officerDashboardFrame = new DashboardPetugas(IDPetugas);
                officerDashboardFrame.setVisible(true);
            } else {
                // Handle other roles if needed
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginClickActionPerformed

    
    private void LoginClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginClickMouseClicked
        String username = Ausername.getText();
        String password = Apassword.getText(); // Retrieve password correctly
        String userRole = getUserRole(username, password);
        
        if (userRole != null) {
            this.dispose(); 
            if (userRole.equals("Manajer")) {
                int IDPetugas = getIDPetugasDatabase(username, password);
                Dashboard adminDashboardFrame = new Dashboard(IDPetugas);
                adminDashboardFrame.setVisible(true);
            } else if (userRole.equals("Kasir")) {
                int IDPetugas = getIDPetugasDatabase(username, password);
                DashboardPetugas officerDashboardFrame = new DashboardPetugas(IDPetugas);
                officerDashboardFrame.setVisible(true);
            } else {
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginClickMouseClicked

    private void ApasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApasswordActionPerformed

    private void AusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AusernameActionPerformed
        // TODO
    }//GEN-LAST:event_AusernameActionPerformed

    private String getUserRole(String username, String password) {

        PreparedStatement statement;
        ResultSet resultSet = null;
        String role = null;

        try {
            
            connection = ConnectionDB.BukaKoneksi();
            if (connection == null) {
                System.out.println("Gagal Nyambung");
                return null;
            }
            
            String query = "SELECT jabatan FROM petugas WHERE username = ? AND password = ?";
                statement = connection.prepareStatement(query);
                statement.setString(1, username);
                statement.setString(2, password);
                resultSet = statement.executeQuery();

            if (resultSet != null && resultSet.next()) {
                role = resultSet.getString("jabatan");
            } else {
                System.out.println("Gagal terkoneksi!");
            }
        } catch (SQLException e) {
            System.out.println(e);
            e.printStackTrace();
        }
        return role;

    }
    
    public int getIDPetugasDatabase(String username, String password) {
        int idPetugas = -1;

        try {
            connection = ConnectionDB.BukaKoneksi();
            if (connection == null) {
                System.out.println("Gagal Nyambung");
                return -1;
            }

            String query = "SELECT id_petugas FROM petugas WHERE username = ? AND password = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, username);
            statement.setString(2, password);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                idPetugas = resultSet.getInt("id_petugas");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } return idPetugas;
} 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apassword;
    private javax.swing.JTextField Ausername;
    private javax.swing.JButton LoginClick;
    private javax.swing.JPanel PanelBackground;
    private com.mycompany.toko_tubes.GradientLogin gradientLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.mycompany.toko_tubes.PanelLoginCustom panelLogin;
    // End of variables declaration//GEN-END:variables
}