/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/*    */package com.mycompany.toko_tubes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.interfaces.RSAKey;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

 public class Pembelian extends javax.swing.JPanel {

     private Connection connection;
    private PreparedStatement preparedStatement;
    private ResultSet resultSet;
    private int IDPetugas;
    
    private void setHargaBarang() {
        try {
         

            String query = "SELECT harga_satuan FROM barang WHERE nama_barang = ?";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, txNamaBarang.getSelectedItem().toString());
            resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                txHargaBarang.setText(resultSet.getString("harga_satuan"));
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        } 
    }
    
    private void txNamaBarangItemChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            setHargaBarang();
        }
    }
    /**
     * Creates new form Pembelian
     */
    public Pembelian(int IDPetugas) {
        initComponents();
        this.IDPetugas = IDPetugas;
         try {
          connection = ConnectionDB.BukaKoneksi();
        } catch (Exception e) {
        }
        populateComboBox(txNamaBarang);
        
        txNamaBarang.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            txNamaBarangItemChanged(evt);
        }
        
        });
        
         refreshButton.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        refreshComboBox();
    }
});
    }
    
    private void populateComboBox(JComboBox comboBox) {
        try {
            String query = "SELECT nama_barang FROM barang";

            preparedStatement = connection.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DefaultComboBoxModel model = new DefaultComboBoxModel();

            while (resultSet.next()) {
                model.addElement(resultSet.getString("nama_barang"));
            }
            comboBox.setModel(model);

        } catch (SQLException ex) {
            ex.printStackTrace();
        } 

    }
    
    public void tambahTransaksi() {
        double jumlah, harga, total;

    jumlah = Double.parseDouble(satuan.getText());
    harga = Double.parseDouble(txHargaBarang.getText());
    total = jumlah * harga;

        loadData(jumlah, harga, total);
        totalBiaya();
        clear2();
    }

    public void loadData(double jumlah, double harga, double total){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{
        txSupplier.getText(),
        txNamaBarang.getSelectedItem().toString(),
        txHargaBarang.getText(),
        jumlah,
        total
        });
       }
        
    public void clear2() {
        txNamaBarang.setSelectedIndex(0);
        txHargaBarang.setText("");
        satuan.setText("");
    }


 public void totalBiaya() {
    int jumlahBaris = jTable1.getRowCount();
    double totalBiaya = 0;

    for (int i = 0; i < jumlahBaris; i++) {
        double jumlahBarang = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        double hargaBarang = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        
        double total = (jumlahBarang * hargaBarang);
        jTable1.setValueAt(total, i, 4);

        totalBiaya += total;
    }
    txTotalHarga.setText(String.valueOf(totalBiaya));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pembelian = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txSupplier = new javax.swing.JTextField();
        satuan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Submit = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txTotalHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txHargaBarang = new javax.swing.JTextField();
        EnterButton = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txTambahBarang = new javax.swing.JTextField();
        txHargaBaru = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        satuanBaru = new javax.swing.JTextField();
        EnterBaru = new javax.swing.JButton();
        ResetBaru = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txNamaBarang = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();

        Pembelian.setBackground(new java.awt.Color(0, 51, 153));
        Pembelian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Keranjang Pembelian");
        Pembelian.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Satuan :");
        Pembelian.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Supplier :");
        Pembelian.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSupplierActionPerformed(evt);
            }
        });
        Pembelian.add(txSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanActionPerformed(evt);
            }
        });
        Pembelian.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Supplier", "Nama Barang", "Harga Barang", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Harga :");

        txTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Pembelian.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 530, 620));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pembelian");
        Pembelian.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Barang  :");
        Pembelian.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Barang  :");
        Pembelian.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txHargaBarang.setEnabled(false);
        txHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaBarangActionPerformed(evt);
            }
        });
        Pembelian.add(txHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 180, -1));

        EnterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EnterButton.setText("ENTER");
        EnterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterButtonMouseClicked(evt);
            }
        });
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });
        Pembelian.add(EnterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reset.setText("RESET");
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        Pembelian.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama Barang :");
        Pembelian.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        txTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTambahBarangActionPerformed(evt);
            }
        });
        Pembelian.add(txTambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 180, -1));

        txHargaBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaBaruActionPerformed(evt);
            }
        });
        Pembelian.add(txHargaBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 180, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Harga Barang  :");
        Pembelian.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Satuan :");
        Pembelian.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        satuanBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanBaruActionPerformed(evt);
            }
        });
        Pembelian.add(satuanBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 180, -1));

        EnterBaru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EnterBaru.setText("ENTER");
        EnterBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterBaruMouseClicked(evt);
            }
        });
        EnterBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBaruActionPerformed(evt);
            }
        });
        Pembelian.add(EnterBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        ResetBaru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResetBaru.setText("RESET");
        ResetBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBaruMouseClicked(evt);
            }
        });
        ResetBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBaruActionPerformed(evt);
            }
        });
        Pembelian.add(ResetBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Dashboard Pembelian");
        Pembelian.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Restock");
        Pembelian.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        Pembelian.add(txNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, -1));

        refreshButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\DEWATA\\Documents\\NetBeansProjects\\TOKO_TUBES\\src\\383083_refresh_reload_icon (1).png")); // NOI18N
        Pembelian.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void DataTransaksi(int IDPetugas) throws SQLException {
    connection.setAutoCommit(false);
    
    double totalPembelian = TotalPembelian();
    
    String insertTransaksiQuery = "INSERT INTO transaksi_pembelian (tanggal_transaksi, total_pembelian, id_petugas, id_suplier) VALUES (NOW(), ?, ?, ?)";
    PreparedStatement insertTransaksiStatement = connection.prepareStatement(insertTransaksiQuery, Statement.RETURN_GENERATED_KEYS);
    insertTransaksiStatement.setDouble(1, totalPembelian);
    insertTransaksiStatement.setInt(2, IDPetugas);
    
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        String supplierName = jTable1.getValueAt(i, 0).toString(); // Nama supplier dari kolom pertama
        String namaBarang = jTable1.getValueAt(i, 1).toString();   // Nama barang dari kolom kedua
        double hargaBarang = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        double jumlahBarang = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        double subtotal = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
 
        int id_supplier = getSupplierID(supplierName);
        insertTransaksiStatement.setDouble(1, totalPembelian);
        insertTransaksiStatement.setInt(2, IDPetugas);
        insertTransaksiStatement.setInt(3, id_supplier);
        insertTransaksiStatement.executeUpdate();

        ResultSet generatedKeys = insertTransaksiStatement.getGeneratedKeys();
        int id_transaksi_pembelian = -1;
        if (generatedKeys.next()) {
            id_transaksi_pembelian = generatedKeys.getInt(1);
        } else {
            throw new SQLException("Creating transaction failed, no ID obtained.");
        }
        
        // Mendapatkan ID barang dari database berdasarkan nama barang
        String sql = "SELECT id_barang FROM barang WHERE nama_barang = ?";
        PreparedStatement ps = connection.prepareStatement(sql);
        ps.setString(1, namaBarang);
        ResultSet rs = ps.executeQuery();
        
        int id_barang = -1;
        if (rs.next()) {
            id_barang = rs.getInt("id_barang"); // Mengambil ID barang dari hasil query
        } else {
            throw new SQLException("Barang not found in database: " + namaBarang);
        }
     
        InsertDetailTransaksi(id_transaksi_pembelian, id_barang, jumlahBarang, subtotal);
        restock(id_barang, jumlahBarang);
        JOptionPane.showMessageDialog(this, "Transaction data has been saved successfully!");
    }
    
    connection.commit();
}

private int getSupplierID(String namaSupplier) throws SQLException {
    String sql = "SELECT id_suplier FROM suplier WHERE nama_suplier = ?";
    PreparedStatement ps = connection.prepareStatement(sql);
    ps.setString(1, namaSupplier);
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        return rs.getInt("id_suplier"); 
    } else {
        String insertSupplierQuery = "INSERT INTO suplier (nama_suplier) VALUES (?)";
        PreparedStatement insertSupplierStatement = connection.prepareStatement(insertSupplierQuery, Statement.RETURN_GENERATED_KEYS);
        insertSupplierStatement.setString(1, namaSupplier);
        insertSupplierStatement.executeUpdate();

        ResultSet generatedKeys = insertSupplierStatement.getGeneratedKeys();
        if (generatedKeys.next()) {
            return generatedKeys.getInt(1); 
        } else {
            throw new SQLException("Failed to add new supplier.");
        }
    }
}


private void InsertDetailTransaksi(int id_transaksi_pembelian, int id_barang, double jumlahBarang, double subtotal) throws  SQLException{
     String query = "INSERT INTO detail_transaksi_pembelian (id_transaksi_pembelian, id_barang, jumlah_barang, subtotal) VALUES (?, ?, ?,?)";
     PreparedStatement pst = connection.prepareStatement(query);
            pst.setInt(1, id_transaksi_pembelian);
            pst.setInt(2, id_barang);
            pst.setDouble(3, jumlahBarang);
            pst.setDouble(4, subtotal);
            pst.executeUpdate();
            System.out.println("Insert Berhasil");
}

private double TotalPembelian() {
    double total = 0.0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double subtotal = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
        total += subtotal;
    }
    return total;
}

private void restock(int id_barang, double jumlahBarang) throws SQLException {
    String updateQuery = "UPDATE barang SET stok = stok + ? WHERE id_barang = ?";
    try (PreparedStatement updateStatement = connection.prepareStatement(updateQuery)) {
        updateStatement.setDouble(1, jumlahBarang);
        updateStatement.setInt(2, id_barang);
        updateStatement.executeUpdate();
    }
}
    private void tambahBarang() throws SQLException { 
        String namaBarang = txTambahBarang.getText();
        if (cekNamaBarang(namaBarang)) {
            JOptionPane.showMessageDialog(this, "Nama barang sudah ada dalam database. Silakan gunakan nama barang lain.");
            return; 
        }
        int id_barang = NewIdBarang();
        String query = "INSERT INTO barang (id_barang, nama_barang, stok, harga_satuan) VALUES (?, ?,?, ?)";
        PreparedStatement pst = connection.prepareStatement(query);
       
            pst.setInt(1, id_barang);
            pst.setString(2, txTambahBarang.getText());
            pst.setDouble(3, Double.parseDouble(satuanBaru.getText()));
            pst.setDouble(4, Double.parseDouble(txHargaBaru.getText()));

            // Execute the insert statement
            pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Transaction data has been saved successfully!");
    }

   private boolean cekNamaBarang(String namaBarang) throws SQLException {
    String query = "SELECT COUNT(*) AS jumlah FROM barang WHERE nama_barang = ?";
    try (PreparedStatement pst = connection.prepareStatement(query)) {
        pst.setString(1, namaBarang);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            int jumlah = rs.getInt("jumlah");
            return jumlah > 0; // Mengembalikan true jika nama barang sudah ada dalam database
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); // Tangani pengecualian SQL
    }
    return false; // Jika terjadi kesalahan, mengembalikan false secara default
    }   
        
    private int NewIdBarang() throws SQLException {
        String idBarangQuery = "SELECT MAX(id_barang) AS max_id FROM barang";
            PreparedStatement idBarangStatement = connection.prepareStatement(idBarangQuery);
            ResultSet rs = idBarangStatement.executeQuery();
        if (rs.next()) {
            int id_barang = rs.getInt("max_id"); 
                    return id_barang + 1; 
        }return 0;
    }
        
    private void refreshComboBox() {
    try {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        String query = "SELECT nama_barang FROM barang";
        preparedStatement = connection.prepareStatement(query);
        resultSet = preparedStatement.executeQuery();

        while (resultSet.next()) {
            model.addElement(resultSet.getString("nama_barang"));
        }

        txNamaBarang.setModel(model);
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
    private void satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try {
            tampilkanStrukBelanja();
            DataTransaksi(IDPetugas);
        } catch (SQLException ex) {
            Logger.getLogger(Pembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearJTable();
    }//GEN-LAST:event_SubmitActionPerformed

    private void txHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaBarangActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        model.removeRow(row);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalHargaActionPerformed

    }//GEN-LAST:event_txTotalHargaActionPerformed

    private void EnterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterButtonMouseClicked
        tambahTransaksi();
    }//GEN-LAST:event_EnterButtonMouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        txSupplier.setText("");
        txNamaBarang.setSelectedItem(null);
        txHargaBarang.setText("");
        satuan.setText("");
    }//GEN-LAST:event_ResetMouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        
    }//GEN-LAST:event_SubmitMouseClicked

    private void txTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTambahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTambahBarangActionPerformed

    private void txSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSupplierActionPerformed

    private void txHargaBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaBaruActionPerformed

    private void satuanBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanBaruActionPerformed

    private void EnterBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterBaruMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterBaruMouseClicked

    private void EnterBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBaruActionPerformed
        try {
            tambahBarang();
        } catch (SQLException ex) {
            Logger.getLogger(Pembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EnterBaruActionPerformed

    private void ResetBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBaruMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBaruMouseClicked

    private void ResetBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBaruActionPerformed
        txTambahBarang.setText("");
        txHargaBaru.setText("");
        satuanBaru.setText("");
    }//GEN-LAST:event_ResetBaruActionPerformed

private void clearJTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear all rows from the table
}

public void tampilkanStrukBelanja() {
    StringBuilder struk = new StringBuilder();
    double totalBelanja = 0.0;

    struk.append("===== Struk Belanja =====\n");

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        String namaBarang = model.getValueAt(i, 1).toString();
        double hargaSatuan = Double.parseDouble(model.getValueAt(i, 2).toString());
        double jumlahBarang = Double.parseDouble(model.getValueAt(i, 3).toString());
        double total = Double.parseDouble(model.getValueAt(i, 4).toString());
        
        struk.append("Nama Barang: ").append(namaBarang).append("\n");
        struk.append("Harga Satuan: ").append(hargaSatuan).append("\n");
        struk.append("Jumlah Barang: ").append(jumlahBarang).append("\n");
        struk.append("Total Harga: ").append(total).append("\n");
        struk.append("\n");

        totalBelanja += total;
    }
    struk.append("Total Belanja: ").append(totalBelanja).append("\n");
    JOptionPane.showMessageDialog(this, struk.toString(), "Struk Belanja", JOptionPane.INFORMATION_MESSAGE);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterBaru;
    private javax.swing.JButton EnterButton;
    private javax.swing.JPanel Pembelian;
    private javax.swing.JButton Reset;
    private javax.swing.JButton ResetBaru;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField satuan;
    private javax.swing.JTextField satuanBaru;
    private javax.swing.JTextField txHargaBarang;
    private javax.swing.JTextField txHargaBaru;
    private javax.swing.JComboBox<String> txNamaBarang;
    private javax.swing.JTextField txSupplier;
    private javax.swing.JTextField txTambahBarang;
    private javax.swing.JTextField txTotalHarga;
    // End of variables declaration//GEN-END:variables
 }