/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.toko_tubes;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEWATA
 */
public class Transaksi extends javax.swing.JPanel {

    private Connection connection;
    private PreparedStatement preparedStatement;
    private ResultSet resultSet;
    
    public Transaksi() {
        initComponents();
        try { 
          connection = DBStock.BukaKoneksi();
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransaksiPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePenjualan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePembelian = new javax.swing.JTable();
        ButtonPembelian = new javax.swing.JButton();
        ButtonPenjualan1 = new javax.swing.JButton();

        TransaksiPanel.setBackground(new java.awt.Color(0, 51, 153));
        TransaksiPanel.setPreferredSize(new java.awt.Dimension(980, 700));
        TransaksiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reporting");
        TransaksiPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Transaksi Pembelian");
        TransaksiPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Transaksi Penjualan");
        TransaksiPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        TablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi Penjualan", "ID Petugas", "Tanggal Transaksi", "Total Penjualan"
            }
        ));
        jScrollPane1.setViewportView(TablePenjualan);

        TransaksiPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 480, 470));

        TablePembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi Pembelian", "ID Suuplier", "ID Petugas", "Tanggal Transaksi", "Total Pembelian"
            }
        ));
        jScrollPane2.setViewportView(TablePembelian);

        TransaksiPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 480, 470));

        ButtonPembelian.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonPembelian.setText("TAMPILKAN");
        ButtonPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPembelianActionPerformed(evt);
            }
        });
        TransaksiPanel.add(ButtonPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, -1, -1));

        ButtonPenjualan1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ButtonPenjualan1.setText("TAMPILKAN");
        ButtonPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPenjualan1ActionPerformed(evt);
            }
        });
        TransaksiPanel.add(ButtonPenjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPembelianActionPerformed
        try {
            String query = "SELECT id_transaksi_pembelian, id_suplier, id_petugas, tanggal_transaksi, total_pembelian FROM transaksi_pembelian";
            preparedStatement = connection.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            // Buat model tabel baru
            DefaultTableModel model = (DefaultTableModel) TablePembelian.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                int idTransaksi = resultSet.getInt("id_transaksi_pembelian");
                int idSuplier = resultSet.getInt("id_suplier");
                int idPetugas = resultSet.getInt("id_petugas");
                String tanggal = resultSet.getString("tanggal_transaksi");
                int total = resultSet.getInt("total_pembelian");

                model.addRow(new Object[]{idTransaksi,idSuplier, idPetugas, tanggal, total });
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ButtonPembelianActionPerformed

    private void ButtonPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPenjualan1ActionPerformed
        try {
            String query = "SELECT id_transaksi_penjualan, id_petugas, tanggal_transaksi, total_penjualan FROM transaksi_penjualan";
            preparedStatement = connection.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            // Buat model tabel baru
            DefaultTableModel model = (DefaultTableModel) TablePenjualan.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                int idTransaksi = resultSet.getInt("id_transaksi_penjualan");
                int idPetugas = resultSet.getInt("id_petugas");
                String tanggal = resultSet.getString("tanggal_transaksi");
                int total = resultSet.getInt("total_penjualan");

                model.addRow(new Object[]{idTransaksi, idPetugas, tanggal, total });
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ButtonPenjualan1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPembelian;
    private javax.swing.JButton ButtonPenjualan1;
    private javax.swing.JTable TablePembelian;
    private javax.swing.JTable TablePenjualan;
    private javax.swing.JPanel TransaksiPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
